### ISSUE TITLE
Reported IOUT current from MDP-P905

### ISSUE THREAD

**Issue by nikolasgd** [ElluIFX/MDP-P906-Controller#2]
Hi there. Awesome project!

I got it connected from my Thinkpad to my MDP-P905.

I noticed the reported output current in your application seems to be about 2x what is displayed on the power supply. Is this a calibration issue?

![image](https://github.com/user-attachments/assets/e4c7c03e-055a-4342-91a0-79fd60c9688d)

![image](https://github.com/user-attachments/assets/8dd294fe-b7ca-40f2-9adb-d68d5dbe6b9e)

![image](https://github.com/user-attachments/assets/93920b6c-c96a-4c9a-a4d7-b6a1aa01ff02)

**Comment by ElluIFX** [comment]
This is strange, I will check it tonight.

**Comment by ElluIFX** [comment]
Maybe you can use the Python API to check the raw readings first, as I have not been able to identify any issues from your screenshot.

Is your firmware up to date?
> https://forum.minidso.com/forum.php?mod=viewthread&tid=3696

Perhaps this problem is caused by the calibration parameter differences reported by P905 and P906. If possible, you can attach the log file to this issue for me to check.

By setting the system environment variable "MDP_ENABLE_LOG" to "1," the software will create a log file. Perform some operations, and then attach the log file to a comment.

If the problem is finally not found, I can add an option to adjust the calibration parameter, allowing you to manually calibrate the current and voltage readings.

**Comment by nikolasgd** [comment]
I have installed the latest firmware on the P905.

I am using the Windows packaged version, is it possible at all to set environmental variables? Will the Python API be able to connect to the USB adapter, if I run the application from within WSL2?

I know how to do all this on my M3 Macbook with Mac OS Sonoma, but there seems to be trouble with the CH340 kernel extension, as all I get is "NRF24-Adapter wait timeout".

**Comment by ElluIFX** [comment]
1. Logging function is also available in release ver, how to set windows env [can look this](https://phoenixnap.com/kb/windows-set-environment-variable), desired result:
![image](https://github.com/user-attachments/assets/b40d1c40-0260-4626-a03b-0174e157018b)
2. python API can work OS independently, I use this on Windows, but it should work fine in WSL2 or macOS, because it just communicates with the USB-Uart chip. This can be helpful if you use wsl2: [nickbeth / wsl-usb-manager](https://github.com/nickbeth/wsl-usb-manager)
3. Sry I haven't used macOS. But this chip is used widely in different hardware, maybe you can find a solution online.

**Comment by nikolasgd** [comment]
Thanks for the explanation.

Here is the log file. I set the M905 to 10 Volts and connected a 25W 10 Ohms resistor.

This time I noticed the current (IOUT) value displayed in the application was exactly 2x of the value displayed on my P905.  This happens only under load. If the current drops to zero on the P905, it will be reflected correctly in the application.

[mdp.log](https://github.com/user-attachments/files/17634237/mdp.log)

**Comment by nikolasgd** [comment]
I will try to get the Python API running on Windows, too, and let you know when I have results.

**Comment by ElluIFX** [comment]
Due to the possibility of being busy with other work in the next two days, I am temporarily unable to track your progress, so I quickly modified and built a new [release version](https://github.com/ElluIFX/MDP-P906-Controller/releases/tag/software).

In this version, you can manually set simple linear calibration parameters to calibrate your device readings, which affects every function including recording and PID control.

The parameters can be fitted by UI reporting data and the actual measurement results obtained with a multimeter, using Excel with y=kx+b, y is the calibrated value and x is the raw reading.

I hope this can temporarily resolve the reading error issue.

Also, the log feature now reports cali params, pls send me a new log file to figure out bugs.

You can continue to report your issues in this issue, and I will address them when I have time.

**Comment by nikolasgd** [comment]
Thank you for the update! I will try the new release soon and sent you a new log file as well as the raw readings, as soon as I get the Python API running.

**Comment by nikolasgd** [comment]
I installed the update and I can display correct IOUT values using Ik=0.5 and Ib=0. That works for me, great!

BTW the voltage and current set on the device are not reflected in the app. Is suspect there is a few differences in the byte order of the raw data transmitted between the P905 vs P906. I will send you the raw readings as soon as I have the RF adapter connected to my Macbook or installed Python on Windows.

**Comment by nikolasgd** [comment]
Do you know if the Python API is reported to work on Mac OS? Because all I get when running test_main.py is:

`Exception: NRF24-Adapter wait timeout`

I know the CH340 driver on my Macbook is working, because I can connect and read from the NRF24L01 adapter with STM32CubeProgrammer via UART. I also use my MacBook to flash the Wemos D1 Mini that uses a CH340 chip.

**Comment by ElluIFX** [comment]
My code uses the unique chip ID of the CH340 to try to find the port number (aka the device path on Unix systems), if you have more than one CH340 connected to the same computer, it will not be able to know which is the correct device, and it will just open the first one. Maybe you can try manually specifying the device path (using `MDP_P906(<other params>, port="/dev/ttyx")`)

This automatic search behavior depends on the list device feature of the pyserial library, and I'm not sure if it can work normally on macOS

**Comment by nikolasgd** [comment]
You mean this ID?

`self._port_name = _find_port_name("1A86:7523")`

That's correct. I have only this one CH340 connected. If I remove the NRF24L01 it will report

"NRF24-Adapter not found"

so I know it can identify it but not communicate with it correctly.

**Comment by ElluIFX** [comment]
I noticed that some people online report that the pyserial library requires additional calls to work reliably on macOS, but some say it doesn't require any modifications. Maybe you can try searching and modifying the parts involving serial ports yourself to fix it.

The part involving serial port reading is in the `SerialReaderBuffered` class in the `serial_reader.py` file, where `self._ser.read` is used for calling the library to read

The part involving serial port writing is in the `_write` method of the `NRF24Adapter` class in the `nrf24_adapter.py` file

The other codes are purely logical processing, not involving library calls.

**Comment by ElluIFX** [comment]
`logger.debug(someoutput)` is useful for debuging, modify the `richuru.install(tracebacks_suppress=[mdp_controller])` to `richuru.install(level="TRACE")` 
 in the beginning of test_main.py will give you complete debug message from hardware processing layer.

**Comment by ElluIFX** [comment]
Certainly, I would recommend using a Linux virtual machine, as I have used this library extensively on Linux and find it very reliable

**Comment by ElluIFX** [comment]
And dont forgot the log file from App, I think the key is in it XD

**Comment by nikolasgd** [comment]
> And dont forgot the log file from App, I think the key is in it XD

Sure here it is:
[mdp.log](https://github.com/user-attachments/files/17650740/mdp.log)

I will see if I can make sense of the serial reading class. Thanks for the information so far.

**Comment by ElluIFX** [comment]
I did indeed find some clues

This is a quick fix preview version:
[test](https://github.com/ElluIFX/MDP-P906-Controller/releases/tag/test)

Please test to see if everything goes fine, good night

**Comment by nikolasgd** [comment]
Works! (current gain and settings) Perfect. Thank you and good night!

**Comment by ElluIFX** [comment]
Glad to see it works, if you have any further questions you can just open another issue.

**Comment by ElluIFX** [comment]
What's more, dont forget to delete the env varible and disable log feature, that's a huge performance cost.

**Comment by nikolasgd** [comment]
I checked it again today and it seems I missed a thing while testing yesterday: only the voltage setting is reflected in the application but not the current setting.

And just an observation: when the app is started and the device is already running, the "on" state is not received from the device, so you have to turn the "on" state on the device off and on again to be able to control it via the app.

**Comment by ElluIFX** [comment]
Alright……I've enabled the raw data log in this version, please do some operations and then let me see the latest log
[test](https://github.com/ElluIFX/MDP-P906-Controller/releases/tag/test)

**Comment by nikolasgd** [comment]
Here you go: 
[mdp.log](https://github.com/user-attachments/files/17660706/mdp.log)

Tried to change voltage and current from the device. Then applied some load and changed current on the device again.

**Comment by ElluIFX** [comment]
What is the actual voltage and current you have set? I have parsed out an extremely large current size from the original data

**Comment by ElluIFX** [comment]
![image](https://github.com/user-attachments/assets/d572bd78-2e64-4a55-934e-ad55685ec0de)
This parsing rule has never failed on P906
It seems this is where the problem lies

**Comment by nikolasgd** [comment]
> What is the actual voltage and current you have set? I have parsed out an extremely large current size from the original data

I cannot say for sure. I just started up the device and it is set to 1A. So it was probably 1A and then I used the scroll wheel and went down milliampers from there.

**Comment by nikolasgd** [comment]
The P905 has a lower maximum power output than the P906.

30 V / 5 A, 90 W (whatever comes first)

**Comment by ElluIFX** [comment]
I guess the control command may have exceeded the range and damaged the P905 feedback data. Can you restart the P905, then connect the device while ensuring that Iset is less than 5A, and see if it operates normally afterwards

If not, it may be that the P905 cannot report its own set current, as the corresponding bit position in the original data is jumping randomly, and each report is different

**Comment by ElluIFX** [comment]
I am writing a feature to identify device models and limit the range

**Comment by nikolasgd** [comment]
> I guess the control command may have exceeded the range and damaged the P905 feedback data. Can you restart the P905, then connect the device while ensuring that Iset is less than 5A, and see if it operates normally afterwards

The device cannot be set to a value larger than 5A. Whatever I set it to, the application will report 10A.

> If not, it may be that the P905 cannot report its own set current, as the corresponding bit position in the original data is jumping randomly, and each report is different

I can confirm that the device can report it's current value, I have seen it displayed on my MDP M01.

**Comment by ElluIFX** [comment]
Is the voltage-set report accurate？

**Comment by nikolasgd** [comment]
Yes, voltage seems accurate

**Comment by nikolasgd** [comment]
Wait, no its not.. checking it again.

**Comment by ElluIFX** [comment]
In this version, P905 recognition has been added, and if the window title changes, check if it works normally.
[test2](https://github.com/ElluIFX/MDP-P906-Controller/releases/tag/test)

**Comment by ElluIFX** [comment]
Actually, it's quite simple, because of the change in range, P906 uses an additional bit to report the current, causing a protocol difference

Miniware uses BCD Code in the protocol is really wired, for me.

**Comment by nikolasgd** [comment]
Not always accurate. When the cursor was in the voltage set input in the app, it would not reflect the change from the device and report irratic value afterwards.

Also I noticed that if I set the current on the device to 0,031A, it will report 3,1A in the application :)

I will download and test your latest version test2 now.

**Comment by nikolasgd** [comment]
I can not connect in the latest version:

![Screenshot 2024-11-07 134256](https://github.com/user-attachments/assets/b0ecb211-3e20-4f15-8d3e-4c918371dbb8)

**Comment by ElluIFX** [comment]
> Not always accurate. When the cursor was in the voltage set input in the app, it would not reflect the change from the device and report irratic value afterwards.

This is intentional; otherwise, the device would continuously report data and change the input box, which would prevent you from adjusting the values

**Comment by ElluIFX** [comment]
Try test3, small mistake, I dont have device now
https://github.com/ElluIFX/MDP-P906-Controller/releases/tag/test

**Comment by nikolasgd** [comment]
test3 from 1 hour ago?

**Comment by nikolasgd** [comment]
ah ok.. 9 minutes ago. my mistake. installing it now

**Comment by nikolasgd** [comment]
Did some testing and can't see no bugs so far! Thank you!

Only the title bar still says P906, but that's not an issue for me.

There is one minor thing I am not sure you are aware of:
Changing the value of voltage or current in the application is not very convenient. Pressing the arrows up in the input field will increment in Millivolts. Entering a decimal numner i.e. "3.3" ("3,3" in my locale) is also not possible. So it takes clicking in the field, moving cursor with cursor keys to digit, change. move cursor to next digit, change again.

I would find it much easier if I could double click in the field, have it automatically select all, and then enter a decimal number to replace what was there before. Similar to the input field in the presets editor below!

**Comment by ElluIFX** [comment]
In fact, this is to imitate the mode in other controller apps where you can select the corresponding digit and adjust the number by scrolling the mouse wheel (such as scrolling by 1, 0.1, 0.001), but the limitations of Qt have made my implementation not as elegant. I will try to optimize this part later tonight when I have the device.

**Comment by nikolasgd** [comment]
I understand. It's just a preference thing. Let me know if you need me for further testing.

**Comment by ElluIFX** [comment]
Additional preference settings (including the ones you mentioned) have been added to the latest release version, you can try to see if they are good for you.

Now, the theme hint color can be adjusted by manually editing the settings.json

**Comment by nikolasgd** [comment]
Awesome, thank you! I love it.

**Comment by ElluIFX** [comment]
I made a fantastic change in the 3.0 version, you must go check it out XD

**Comment by nikolasgd** [comment]
Oh I will try it as soon as I get back to my office where I keep my Thinkpad, could be tomorrow or Monday.

**Comment by nikolasgd** [comment]
Awesome! Development is ongoing. A really useful app. On a side note: I find the auxiliary function menu items a bit fiddly to select. I have to hit a tiny arrow to reveal further menu options. And may I suggest you display the version number somewhere in the app?

**Comment by ElluIFX** [comment]
The version number will be added in the next update. The issue of overlapping text and arrows in the auxiliary menu seems to be caused by PyQt, which is not easy to fix, so using the mouse wheel for navigation is recommended.
